blank_issues_enabled: true
contact_links:
  - name: Report a security issue
    url: https://github.com/Stakely/lido-withdrawals-automation/security/policy
    about: Learn how to report a security issue
